import pygame

TITLE_CALL_VISIT = "Call or Visit"
TEXT_CALL_VISIT = "Do something simple: Call your grandparents, friends, visit your family..."
TEXT_CALL_VISIT_DOWN = "Even the smallest action can change someone's day!"
TEXT_CV_SIZE = 22
TEXT_CV_LOCATION = (75, 150)
TEXT_CV_LOCATION_DOWN = (95, 440)
TEXT_CV_SIZE_DOWN = 25
PLAY_PHONE_PHOTO = pygame.image.load('phone.png')
PLAY_PHONE_PHOTO = pygame.transform.scale(PLAY_PHONE_PHOTO, (200, 150))
PLAY_GRANDMA_PHOTO = pygame.image.load('grandma.png')
PLAY_GRANDMA_PHOTO = pygame.transform.scale(PLAY_GRANDMA_PHOTO, (200, 250))

TITLE_SMILE = 'Smile to the world'
TEXT_SMILE1 = 'If you go outside today,'
TEXT_SMILE2 = 'Smile !'
TEXT_SMILE3 = "It can make someone's day!"
TITLE_SMILE_SIZE = 70
TITLE_SMILE_LOCATION = (90, 20)
TEXT_SMILE1_LOCATION = (150,120)
TEXT_SMILE2_LOCATION = (270,190)
TEXT_SMILE3_LOCATION = (120,270)
TEXT_1_3_SIZE = 50
TEXT_2_SIZE = 80
PLAY_SMILE_PHOTO = pygame.image.load('smile_2.png')
PLAY_SMILE_PHOTO = pygame.transform.scale(PLAY_SMILE_PHOTO, (170, 170))


# food donate
TITLE_FOOD = 'Food Donation'
TITLE_FOOD_SIZE = 90
TITLE_FOOD_LOCATION = (90, 20)
TEXT_FOOD_1 = 'Choose a city:'
TEXT_FOOD_SIZE = 50
TEXT_FOOD_LOCATION = (90, 130)
CITY_BUTTON_PHOTO = pygame.image.load('screen2_button.png')
CITY_BUTTON_PHOTO = pygame.transform.scale(CITY_BUTTON_PHOTO, (200, 100))
FIRST_BUTTON_TEXT = "Tel Aviv"
FIRST_BUTTON_COLOR = (255, 255, 255)
FIRST_BUTTON_SIZE = 30
FIRST_BUTTON_LOCATION = (120, 225)
SECOND_BUTTON_TEXT = "Jerusalem"
SECOND_BUTTON_COLOR = (255, 255, 255)
SECOND_BUTTON_SIZE = 30
SECOND_BUTTON_LOCATION = (325, 225)
THIRD_BUTTON_TEXT = "Petah Tikva"
THIRD_BUTTON_COLOR = (255, 255, 255)
THIRD_BUTTON_SIZE = 30
THIRD_BUTTON_LOCATION = (530, 225)

AFTER_CHOOSE_CITY_TEXT = 'Go to one of the following:'
AFTER_CHOOSE_CITY_TEXT_SIZE = 40
AFTER_CHOOSE_CITY_TEXT_LOCATION = (100, 300)


TEL_AVIV_ADDRESS1= "Latet- Hamasger 44"
TEL_AVIV_ADDRESS2 = 'Hasdei Neomy- Tishrei 54'
JERUSALEM_ADDRESS1 = 'Meir panim- Hazvi 11'
JERUSALEM_ADDRESS2 = 'Mazon Lahaim- Ben Yehoda 2'
PETAH_TIKVA_ADDRESS1 = 'Pithon Lev- Zabotinsky 4'
PETAH_TIKVA_ADDRESS2 = 'Mazon Lahaim- Macabim 17'

ADDRESS_SIZE = 30
ADDRESS1_LOCATION = (100, 370)
ADDRESS2_LOCATION = (100, 420)

THANK_YOU_TEXT = 'Thank you fot helping the community!'
THANK_YOU_TEXT_SIZE = 20
THANK_YOU_TEXT_LOCATION = (150, 470)

NOTE_PHOTO = pygame.image.load('note.png')
NOTE_PHOTO = pygame.transform.scale(NOTE_PHOTO, (200, 200))

SHOPPING_LIST_TITLE = 'You should bring:'
SHOPPING_LIST_TITLE_SIZE = 20
SHOPPING_LIST_TITLE_LOCATION = (570, 330)
SHOPPING_LIST_PRODUCT_SIZE = 15
SHOPPING_LIST_PRODUCT_1_LOCATION = (590, 360)
SHOPPING_LIST_PRODUCT_2_LOCATION = (590, 385)
SHOPPING_LIST_PRODUCT_3_LOCATION = (590, 410)
SHOPPING_LIST_PRODUCT_4_LOCATION = (590, 435)
PRODUCT_1 = '- Bread'
PRODUCT_2 = '- Milk'
PRODUCT_3 = '- Rice'
PRODUCT_4 = '- Meat'

# recycling
GREEN_BIN_PHOTO = pygame.image.load('green bin.png')
GREEN_BIN_PHOTO = pygame.transform.scale(GREEN_BIN_PHOTO, (170, 200))
ORANGE_BIN_PHOTO = pygame.image.load('orange bin.png')
ORANGE_BIN_PHOTO = pygame.transform.scale(ORANGE_BIN_PHOTO, (170, 200))
BLUE_BIN_PHOTO = pygame.image.load('blue bin.png')
BLUE_BIN_PHOTO = pygame.transform.scale(BLUE_BIN_PHOTO, (170, 200))

RECYCLING_TITLE = 'Recycling'
RECYCLING_TITLE_SIZE = 90
RECYCLING_TITLE_LOCATION = (180, 20)

GREEN_BIN_GAR = 'Organic garbage'
GREEN_BIN_GAR_SIZE = 60
GREEN_BIN_GAR_LOCATION = (70, 350)

ORANGE_BIN_GAR = 'Plastic, metals'
ORANGE_BIN_GAR_SIZE = 60
ORANGE_BIN_GAR_LOCATION = (250, 350)

BLUE_BIN_GAR = 'Papers'
BLUE_BIN_GAR_SIZE = 60
BLUE_BIN_GAR_LOCATION = (520, 350)
